In [2]:
import pandas as pd

In [5]:
data1={
    "Emp_id":["E01","E02","E03","E04","E05"],
    "Name":["Ram","Sham","Avinash","Rahul","Ravi"],
    "Age":[34,90,10,75,10]
}

data2={
    "Emp_id":["E01","E02","E03","E04","E05"],
    "Salary":[4500,2344,1880,7499,8460]
}

df4=pd.DataFrame(data1)
df5=pd.DataFrame(data2)

In [6]:
print(df4)
print()
print(df5)

  Emp_id     Name  Age
0    E01      Ram   34
1    E02     Sham   90
2    E03  Avinash   10
3    E04    Rahul   75
4    E05     Ravi   10

  Emp_id  Salary
0    E01    4500
1    E02    2344
2    E03    1880
3    E04    7499
4    E05    8460

In [7]:
pd.merge(df4,df5,on="Emp_id") # join the basis of emp id

  Emp_id     Name  Age  Salary
0    E01      Ram   34    4500
1    E02     Sham   90    2344
2    E03  Avinash   10    1880
3    E04    Rahul   75    7499
4    E05     Ravi   10    8460

In [8]:
pd.merge(left=df4,right=df5,on="Emp_id",how="left")
#left join

  Emp_id     Name  Age  Salary
0    E01      Ram   34    4500
1    E02     Sham   90    2344
2    E03  Avinash   10    1880
3    E04    Rahul   75    7499
4    E05     Ravi   10    8460